### PR TITLE
Add confirm button to user detail in admin UI

### PR DESCRIPTION
**Pull request by ricco24**

### CODE REVIEW

**Comment by rootpd** [comment]
@ricco24 What's the purpose of `byAdmin` flag? Are you planning to use it / do you think it might be useful for somebody?

_(I don't see a scenario for this and I'd probably try not to complicate the interface without an actual use case at this point)_

**Comment by ricco24** [comment]
Only for mailing purposes. Manual user confirmation will send email and confirmation from admin UI doesn't.

But this is not our real scenario now.

**Comment by ricco24** [comment]
What with this?

**Comment by markoph** [comment]
Hi, sorry we forgot to add this into release notes. I fixed it [0.17.0](https://github.com/remp2020/crm-users-module/releases/tag/0.17.0)

We had to do some internal changes in our system and your commits were squashed within merge. Squash is probably reason why Github didn't automatically marked this pull request as "merged".

Commit is here: https://github.com/remp2020/crm-users-module/commit/ddd366e8178705f64d5ea0ce9061c174d5b1f866

Since it was internally squashed I am closing this PR. Thank you for your contribution.

**Pull request closed without merging**
