### PR TITLE
Add german translation to module

### PR DESCRIPTION
**Pull request by alexmerz**

### CODE REVIEW

**Comment by rootpd** [comment]
Hi Alex, this is amazing. I'm not sure whether you saw, but we use Weblate for translations. You can work on the translation of any module there: https://hosted.weblate.org/projects/remp-crm/

Currently the translations can be added only by selected users, so let me know if you'll create an account there and I can give you an access.

(we'll merge this, no need to duplicate the work there)

**Comment by alexmerz** [comment]
Hi!
I registered with weblate also using the username alexmerz. I would be happy to provide further translations.

Best!

**Comment by rootpd** [comment]
Great. I gave you a level of access that should be sufficient. Let me know if you're able to start a new translation (since there's no german yet), or whether we need to add german language first.

**Comment by alexmerz** [comment]
I tried it and it looks like you need to approve it.

**Comment by rootpd** [comment]
Weird, I can't see any kind of notification. Which module you're trying to translate?

**Comment by alexmerz** [comment]
The application module
https://hosted.weblate.org/projects/remp-crm/application-module/

**Comment by rootpd** [comment]
OK, I've got the notification, but the available locales are all weird. It's either `de` or `de_DE@rude`. Not sure if you're familiar with that `rude`, but I'm not :).

Just to be sure it's all OK, I will manually create `de_DE` language files in the all modules and push them tomorrow. After that, Weblate will pick up the language and adds a new translation.

**Comment by alexmerz** [comment]
All the de-Options looked somewath obscure, but use whatever looks to fit for you. I see forward to contribute to the other modules!

**Comment by rootpd** [comment]
Hi Alex, the users module is now imported in weblate, it looks great! There are couple of failing checks that weblate automatically does, you can review them at https://hosted.weblate.org/projects/remp-crm/users-module/de/. Usually it's a `.` character missing/not missing at the end of the translated string and these kind of things.

We've also added empty german translation files to the remaining modules, you're free to continue in Weblate.

I might have accidentally removed your application module changes if they were already there (I think they were). I struggled a bit with Weblate to tell it to use `de_DE.yml` files and the application module had only `de.yml` translation file.  Sorry for that.

You can now continue here: https://hosted.weblate.org/languages/de/remp-crm/

Thanks again for the contribution :)

**Comment by alexmerz** [comment]
Hi Peter, I'm very much done with the needed translations in weblate for the most important modules.

**Comment by rootpd** [comment]
Thanks a lot, we've merged it to the internal monorepo master and it will be available in the next CRM release.

**Comment by rootpd** [comment]
I've updated the master, translations from all of the modules are now available. We're planning a tagged 1.2.0 release right after we finish with the Google pay/Apple pay implementation, which should hopefully be early next week.

I'll close this PR, since it wouldn't be able to merge it with the commits I've just pushed. Don't worry, you're still the author there, so the contribution is public :). Thanks again for that.

**Pull request closed without merging**
