### PR TITLE
Removed LOWER() from email

### PR DESCRIPTION
**Pull request by mikoczy**
Usage of the LOWER() mysql function in this case causes a very slow query execution when working with a relatively large database of users (the email index is not used). The collation of the email field is case insensitive (utf8mb4_unicode_ci), so this would give the same results. This way the email index gets used, and the query is much more faster. What do you think?

Thanks

### CODE REVIEW

**Comment by ricco24** [comment]
👍

**Comment by rootpd** [comment]
Reasonable change. Can we do two more ammends so this won't break for existing installations? I'm afraid that people might have been registering with UPPER/CamelCase emails and then tried to log in with lowercase.

* Migration to users module to make each email in the database lowercase.
* Change in `UsersRepository::add` to lowercase the email during insert to the database

**Comment by mikoczy** [comment]
Sure, but it won't really affect the functionality. The following query `select * from users where email="user@user.sk"` will already match all of the following email addresses: USER@USER.SK, User@User.sk, ušer@ušer.sk

**Comment by rootpd** [comment]
:scream: wow. I actually hate mysql for this kind of magic. no need to convert anything as it looks you [need to be explicit](https://dev.mysql.com/doc/refman/5.7/en/case-sensitivity.html) on case sensitivity when creating the column.

Tested on local MySQL and production Percona instances, both work fine. I'll be merging the change as is right now.

**Comment by mikoczy** [comment]
great, thank you

**Comment by rootpd** [comment]
I'm not sure how to tell the github it's merged, but it's merged.. I had to take the patch, apply it in our monorepo and split it to get to this state, so probably that's something Github doesn't accept automatically.

https://github.com/remp2020/crm-users-module/commit/f1637e1dd837816d75f701dc400a9e8f4eff8a92

**Comment by rootpd** [comment]
I'll be making a tagged version after all pending stuff is merged.

**Pull request closed without merging**
